const db = require('../config/db');
const crypto = require('crypto');

// Generate a share link
exports.shareFile = async (req, res) => {
    try {
        const { file_id, expiresInDays } = req.body;
        
        // Verify the file belongs to the user
        const [files] = await db.query('SELECT * FROM files WHERE id = ? AND user_id = ?', [file_id, req.user.id]);
        if (files.length === 0) {
            return res.status(404).json({ error: 'File not found or unauthorized' });
        }

        // Generate a random token
        const token = crypto.randomBytes(16).toString('hex');
        
        let expiresAt = null;
        if (expiresInDays) {
            expiresAt = new Date();
            expiresAt.setDate(expiresAt.getDate() + parseInt(expiresInDays));
        }

        await db.query(
            'INSERT INTO shared_files (file_id, token, expires_at) VALUES (?, ?, ?)',
            [file_id, token, expiresAt]
        );

        // Log Activity
        await db.query('INSERT INTO activity_logs (user_id, action, target_type, target_id) VALUES (?, ?, ?, ?)', 
            [req.user.id, 'SHARE_FILE', 'FILE', file_id]);

        res.json({ token, expires_at: expiresAt });
    } catch (err) {
        console.error(err.message);
        res.status(500).send('Server Error');
    }
};

// Get file by share token
exports.getSharedFile = async (req, res) => {
    try {
        const { token } = req.params;

        const [shared] = await db.query(`
            SELECT s.*, f.file_name, f.file_url, f.file_type, f.file_size 
            FROM shared_files s 
            JOIN files f ON s.file_id = f.id 
            WHERE s.token = ? AND s.is_active = TRUE
        `, [token]);

        if (shared.length === 0) {
            return res.status(404).json({ error: 'Invalid or inactive share link' });
        }

        const shareData = shared[0];

        // Check expiration
        if (shareData.expires_at && new Date(shareData.expires_at) < new Date()) {
            // Expired
            await db.query('UPDATE shared_files SET is_active = FALSE WHERE id = ?', [shareData.id]);
            return res.status(400).json({ error: 'Share link has expired' });
        }

        res.json({
            file_name: shareData.file_name,
            file_url: shareData.file_url,
            file_type: shareData.file_type,
            file_size: shareData.file_size,
            expires_at: shareData.expires_at
        });
    } catch (err) {
        console.error(err.message);
        res.status(500).send('Server Error');
    }
};

// Get all shares generated by the current user
exports.getMyShares = async (req, res) => {
    try {
        const userId = req.user.id;
        
        const [shares] = await db.query(`
            SELECT s.id as share_id, s.token, s.expires_at, s.is_active, s.created_at, 
                   f.id as file_id, f.file_name, f.file_type, f.file_size
            FROM shared_files s
            JOIN files f ON s.file_id = f.id
            WHERE f.user_id = ?
            ORDER BY s.created_at DESC
        `, [userId]);
        
        res.json(shares);
    } catch (err) {
        console.error(err.message);
        res.status(500).send('Server Error');
    }
};

// Revoke a share link
exports.revokeShare = async (req, res) => {
    try {
        const { id } = req.params;
        const userId = req.user.id;

        // Verify the share belongs to a file owned by the user
        const [shares] = await db.query(`
            SELECT s.id 
            FROM shared_files s
            JOIN files f ON s.file_id = f.id
            WHERE s.id = ? AND f.user_id = ?
        `, [id, userId]);

        if (shares.length === 0) {
            return res.status(404).json({ error: 'Share not found or unauthorized' });
        }

        // Delete the share (or we could just set is_active = FALSE)
        await db.query('DELETE FROM shared_files WHERE id = ?', [id]);

        res.json({ message: 'Share link revoked successfully' });
    } catch (err) {
        console.error(err.message);
        res.status(500).send('Server Error');
    }
};
